### ISSUE TITLE
Question: builds for other distros than ubuntu?

### ISSUE THREAD

**Issue by hmalphettes** [dockerfile/redis#1]
Hi there and thanks for maintaining this.
I would like to know if you guys would consider other tags based on different distro or if in fact the best practice is for that to happen elsewhere.
For example: would you consider making a `wheezy` branch for an image based on debian:wheezy?
Here is what it could look like: https://github.com/hmalphettes/dockerfile-redis/tree/wheezy
Thanks for your attention.

**Comment by pilwon** [comment]
@hmalphettes Wheezy is arguably a better distro choice due to its compact size and stability, however most of users of `Dockerfile Project` seem to favor Ubuntu over Debian and they are happy with the way it is. Tagging Docker images is reserved for tagging different versions, therefore instead of creating branches for other distros, it'd be better if someone starts a new project, maybe a sister project of `Dockerfile Project`. If you'd be interested in starting this let me know.

**Comment by hmalphettes** [comment]
@pilwon thanks and thanks for maintaining dockerfile.

I am interested in such a sister project.
I have noticed that @hanswesterbeek has created a handful of `debian:wheezy` based images.
I have also ported a couple of other images from dockerfile's ubuntu to `debian:wheezy`.

@hanswesterbeek would you be interested?
